### ISSUE TITLE
always use DID in ozone URL paths, not handle

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/ozone-ui#18]
For the public web app, we use handles in URL paths because they are human-readable (though this decision has big trade-offs).

For Ozone, we should stick to only using DIDs in paths. If a path or link is clicked that has a handle, it should redirect to the DID version.

The motivation for this is that bad actor accounts frequently cycle handles, which breaks ozone URLs, which is needless churn.

**Comment by foysalit** [comment]
Resolved with #24
